# github: [NickScherbakov] # Если GitHub Sponsors будет активирован
custom:
  - https://www.patreon.com/NinelGPT
  - https://opencollective.com/nick-scherbfkov
  - https://liberapay.com/Nick_Scherbakov/
